---
- name: create service
  template: 
    src: templates/service.j2
    dest: /etc/systemd/system/{{service_name}}
    mode: 0644
- name: create timer
  template:
    src: templates/timer.j2
    dest: /etc/systemd/system/{{timer_name}}
    mode: 0644

- name: Start timer
  systemd:
    name: "{{ timer_name }}"
    state: started
    enabled: true
    daemon_reload: true
- name: start service
  systemd:
    name: "{{ service_name }}"
    state: started
    enabled: true

 
...


