# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "dkd/ubuntu-1804-lvm"


  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ed25519.pub").first.strip

  config.vm.define "bootdemo" do |bootdemo|
    bootdemo.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    bootdemo.vm.hostname = "bootdemo"
    bootdemo.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
    bootdemo.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
    bootdemo.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false

  end


end
