---
##### Установка утилит
- include_tasks: ../../common/tasks/install_utils.yml
##### Настройка времени
- include_tasks: ../../common/tasks/setup_time.yml

#####  Установка docker
- name: Очистка старых версий Docker
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - docker.io
    - docker-doc
    - docker-compose
    - podman-docker
    - containerd
    - runc
  ignore_errors: yes
- name: Установка вспомогательных утилит
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes
- name: Создание каталога для ключа репозитория
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
- name: Загрузка ключа  Docker GPG
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
- name: Добавление репозитория Docker
  apt_repository:
    repo: >-
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/ubuntu
      {{ ansible_facts.lsb.codename }}
      stable
    state: present
    filename: docker
    update_cache: yes
- name: Установка Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: yes
- name: Запуск сервиса Docker  
  service:
    name: docker
    state: started
    enabled: yes
##### Установка Prometheus, Grafana...
- name: Создание каталога для docker compose
  file:
    path: "{{ compose_dir }}"
    state: directory
    mode: 0755

- name: Передача настроек Prometheus
  template:
    src: prometheus.yml.j2
    dest: "{{ compose_dir }}/{{ prometheus_config }}"
    mode: 0644

- name: Передача настроек источников данных  Prometheus
  template:
    src: datasource.yml.j2
    dest: "{{ compose_dir }}/datasource.yml"
    mode: 0644

- name: Передача настроек Alertmanager
  template:
    src: alertmanager.yml.j2
    dest: "{{ compose_dir }}/{{ alertmanager_config }}"
    mode: 0644

- name: Передача настроек бота Telegram
  template:
    src: telegram.tmpl.j2
    dest: "{{ compose_dir }}/{{ telegram_template }}"
    mode: 0644

- name: Передача настроек правил алертов
  template:
    src: alert.rules.yml.j2
    dest: "{{ compose_dir }}/{{ alert_rules }}"
    mode: 0644

- name: Передача настроек Loki
  template:
    src: loki-config.yaml.j2
    dest: "{{ compose_dir }}/loki-config.yaml"
    mode: 0644

- name: Передача источника данных Loki для Grafana
  template:
    src: loki-datasource.yml.j2
    dest: "{{ compose_dir }}/loki.yml"
    mode: 0644
##### Запуск docker compose
- name: Передача файла Docker Compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ compose_dir }}/docker-compose.yml"
    mode: 0644
  notify: Restart stack

- name: Запуск контейнеров Docker Compose
  command: docker compose -f docker-compose.yml up -d
  args:
    chdir: "{{ compose_dir }}"
  register: compose_output
  changed_when:
    - "'Creating' in compose_output.stdout"
    - or "'Recreating' in compose_output.stdout"


