---
- name: Продвижние реплики PostgreSQL Database-1 до мастера
  hosts: db1
  become: yes
  vars:
    postgres_user: ******
    postgres_password: "********"
    postgres_db: postgres
    postgres_port: 5432

  tasks:
    - name: Продвигаем реплику до мастера
      become_user: postgres
      community.postgresql.postgresql_query:
        query: "SELECT pg_promote(true, 60);"  # Ждать 60 секунд
        login_host: "{{ ansible_eth1.ipv4.address }}"
        login_user: "{{ postgres_user }}"
        login_password: "{{ postgres_password }}"
        login_db: "{{ postgres_db }}"
        port: "{{ postgres_port }}"

- name: Настраиваем L4 Proxy на работу с Database-1
  hosts: web
  become: yes
  tasks:
  - name: Загружаем конфигурацию
    template:
      src: "pgstream53.conf.j2"
      dest: "/etc/angie/stream-enabled/pgstream.conf"
      mode: 0644
  - name: Перезагружаем Angie
    systemd:
      name: angie
      state: reloaded
