{
 "title": "Дашборд к ДЗ №21 тема Мониторинг Prometeus-Grafana (Шаров Анатолий)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Load average ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" },
    { "expr": "node_load15", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "__auto" },
    {
     "expr": "node_memory_MemTotal_bytes-node_memory_MemFree_bytes-(node_memory_Cached_bytes + node_memory_Buffers_bytes + node_memory_SReclaimable_bytes)",
     "legendFormat": "__auto"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" },
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius * on(chip) group_left(chip_name) node_hwmon_chip_names",
     "legendFormat": "{{ chip_name }} {{ sensor }}"
    }
   ]
  },
  {
   "title": "Network Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total[$__rate_interval])*8",
     "legendFormat": "Recv {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total[$__rate_interval])*8  ",
     "legendFormat": "Transm {{device}}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[$__rate_interval])",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "irate(node_disk_written_bytes_total[$__rate_interval])",
     "legendFormat": "Write {{device}}"
    }
   ]
  }
 ]
}