global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus_master'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter_host'
    scrape_interval: 5s
    static_configs:
      - targets: ['node_exporter:9100']
