- name: Update apt cache & install common utils
  apt:
    name:
      - net-tools
      - htop
      - mc
      - wget
      - unzip
      - apt-transport-https
      - software-properties-common
      - curl
      - gpg
    update_cache: true
    state: latest
