- name: Создание нового кластера PostgreSQL
  command: pg_createcluster {{ pg_version }} {{ pg_cluster }} --datadir={{ pg_data_dir }} --locale=ru_RU.UTF-8 --port=5432 
  register: create_cluster
- name: Передача конфигурации PostgreSQL
  template:
    src: postgresql.conf.j2
    dest: /etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/postgresql.conf
    mode: 0644
- name: Передача конфигурации доступов hba
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/pg_hba.conf
    mode: 0644
- name: Запуск кластера PostgreSQL
  service:
    name: postgresql
    state: started
    enabled: yes

- name: Ожидание запуска кластера PostgreSQL
  wait_for:
    port: 5432
    delay: 5
    timeout: 60

- name: Создание пользователя с ролью SUPERUSER
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: SUPERUSER

- name: Создание базы с локалью  ru_RU.UTF-8
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"
    encoding: UTF8

- name: Создание пользователя для репликации
  become_user: postgres
  postgresql_user:
    name: repluser
    password: "qq1qq2qq3"
    role_attr_flags: REPLICATION
  ignore_errors: true

