- name: Установка вспомогательных утилит 
  apt:
    name:
      - net-tools
      - htop
      - mc
      - wget
      - unzip
      - apt-transport-https
      - software-properties-common
      - curl
      - gpg
      - ca-certificates
      - auditd
    update_cache: true
    state: latest
