Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 2
  end
  boxes = [
    { :name => "log",
      :ip => "192.168.57.11",
    },
    { :name => "web",
    :ip => "192.168.57.12",
    },
    { :name => "comp",
      :ip => "192.168.57.13",
    },
  ]
  boxes.each do |opts|
    config.vm.define opts[:name] do |config|
      config.vm.hostname = opts[:name]
      config.vm.network "private_network", ip: opts[:ip]
   end
  end
end

