# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|
  config.vm.box = "almalinux/9"

#  config.vm.provision "ansible" do |ansible|
#    ansible.verbose = "vvv"
#    ansible.playbook = "playbook.yml"
#    ansible.become = "true"
#  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_ed25519.pub").first.strip

  config.vm.define "rpmtest" do |rpmtest|
    rpmtest.vm.network "public_network", ip: "192.168.1.138"
    rpmtest.vm.hostname = "rpmtest"
    rpmtest.vm.provision 'shell', inline: 'mkdir -p /root/.ssh'
    rpmtest.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /root/.ssh/authorized_keys"
    rpmtest.vm.provision 'shell', inline: "echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys", privileged: false

    #nfss.vm.provision "shell", path: "nfss_script.sh"
  end


end
