---
# tasks file for modify_nginx
  - name: install nginx
    package:
      name: nginx
      state: present
  - name: create service
    ansible.builtin.template:
      src: templates/service.j2
      dest: /etc/systemd/system/nginx@.service
  - name: create conf1
    ansible.builtin.template:
      src: templates/conf1.j2
      dest: /etc/nginx/nginx-first.conf
  - name: create conf1
    ansible.builtin.template:
      src: templates/conf2.j2
      dest: /etc/nginx/nginx-second.conf
  - name: start nginx1
    systemd:
      name: nginx@first
      state: started
  - name: start nginx2
    systemd:
      name: nginx@second
      state: started

