Vagrant.configure("2") do |config|
    # Указываем ОС, версию, количество ядер и ОЗУ
#    config.vm.box = "generic/centos8"
#    config.vm.box_version = "20210210.0"

    config.vm.provider :virtualbox do |v|
      v.memory = 2048
      v.cpus = 1
    end

    # Указываем имена хостов и их IP-адреса
    boxes = [
      { :box_name => "generic/centos8",
        :name => "ipa.otus.lan",
        :ip => "192.168.57.10",
      },
      { :box_name => "centos/stream9",
        :name => "client1.otus.lan",
        :ip => "192.168.57.11",
      },
      { :box_name => "centos/stream9",
        :name => "client2.otus.lan",
        :ip => "192.168.57.12",
      }
    ]
    # Цикл запуска виртуальных машин
    boxes.each do |opts|
      config.vm.define opts[:name] do |config|
        config.vm.box = opts[:box_name]
        config.vm.hostname = opts[:name]
        config.vm.network "private_network", ip: opts[:ip]
      end
    end
  end
